---
title: "KOGPSY II"
description: |
  Welcome to the website for *Kognitionspsychologie II* FS25 ([23263-02](https://vorlesungsverzeichnis.unibas.ch/de/vorlesungsverzeichnis?id=288841))
  
  Instructors: [Loreen Tisdall](https://loreentisdall.github.io), [Max Theisen](https://psychologie.unibas.ch/de/personen/maximilian-theisen/), [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/), University of Basel
  
  **Last updated:** `r format(Sys.time(), "%a %b %d %X %Y")`
  
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

![Where does motivation come from? <span>Photo by <a href="https://unsplash.com/@anniespratt?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Annie Spratt</a> on <a href="https://unsplash.com/photos/a-piece-of-paper-with-a-message-written-on-it-0Qo_Nn5wLOc?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a></span>](photos/annie-spratt-0Qo_Nn5wLOc-unsplash.jpg)

# Session information

Sessions take place Tuesdays, 10.15-11.45, Biozentrum, Maurice E. Müller Saal U1.111. 

Please note that the **Exam** takes place on 03.06.2025, from	08.00 to 10.00, at the DSBG Neubau, Sporthalle 1. The **Repeat Exam** is scheduled for 21.07.2025, from	10.00 to 12.00, at the Biozentrum, Hörsaal U1.131. 

::: l-body
| # | Date     | Topic                         | Slides | Instructor |
|---| ---------|-------------------------------|--------| ------- |
| 1 | 18.02.2025 | Session 1: Introduction | [pdf](index.html) | Mata |
| 2 | 25.02.2025 | Session 2: TBD | [pdf](index.html) | Mata |
| 3 | 18.03.2025 | Session 4: TBD | [pdf](index.html) | Mata |
| 4 | 25.03.2025 | Session 5: TBD | [pdf](index.html) | Mata |
| 5 | 01.04.2025 | Session 6: TBD | [pdf](index.html) | Mata |
| 6 | 08.04.2025 | Session 7: TBD | [pdf](index.html) | Mata |
| 7 | 15.04.2025 | Session 8: TBD | [pdf](index.html) | Mata |
| 8 | 29.04.2025 | Session 10: TBD | [pdf](index.html)  | Mata |
| 9 | 06.05.2025 | Session 11: TBD | [pdf](index.html) | Mata |
| 10 | 13.05.2025 | Session 12: TBD | [pdf](index.html)  | Mata |
|11 | 20.05.2025 | Session 13: Wrap-up and Q&A | [pdf](index.html) | Mata |
|12 | 03.06.2025 | Exam (DSBG Neubau) |  |  |
|13 | 03.06.2025 | Repeat Exam (Biozentrum)|  |  |
:::

# What is this course about?

This course aims to give a broad introduction to central topics in psychology, with a focus on motivation and emotion. 

# What can you expect to learn?

By completing the course you can expect to...

- learn about central theories and models in key areas of the psychology of motivation and emotion
- become familiarized with common methods used in the psychology of motivation and emotion
- learn about examples of applications of psychology to real-world contexts

# How should you use this website?

This website is designed to help course participants get an overview of the course, including a listing of recommended readings (see below) and the course slides (see table above). A [FAQ](https://adam.unibas.ch/goto_adam_crs_1847406.html) forum is available on ADAM. 

**Recommended Readings**

**Session 1**

TBD

**Session 2**

TBD

**Session 3**

TBD

**Session 4**

TBD

**Session 5**

TBD

**Session 6**

TBD

**Session 7**

TBD

**Session 8**

TBD

**Session 9**

TBD

**Session 10**

TBD
